services:
  db:
    image: postgres:16-alpine
    container_name: utos-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-utos}
      POSTGRES_USER: ${POSTGRES_USER:-utos}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-utos}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-utos} -d ${POSTGRES_DB:-utos}"]
      interval: 10s
      timeout: 5s
      retries: 5
